[package]
name = "dropshot-test"
version = "0.1.0"
authors = ["Benjamin Kircher <bkircher@0xadd.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dropshot = "0.5.1"
tokio = { version = "1", features = ["full"] }
